### ISSUE TITLE
Issue with thief being used as middle piece

### ISSUE THREAD

**Issue by nguyen37** [Xenogents/LegionSolver#33]
![Capture1](https://user-images.githubusercontent.com/25283247/199134061-8f964e4d-2a44-4ea3-b3af-d67b1ec57c95.JPG)
![Capture](https://user-images.githubusercontent.com/25283247/199134062-febecd4b-f776-4bd5-9426-b2b32ad22029.JPG)
Trying to put the thief block in the middle doesnt work in game.  I think an exception should be made to not use it as the first/middle block. It will not go into the orientation shown using the legion solver.

**Comment by Xenogents** [comment]
I'm confused, it looks like you already successfully placed it in the
middle?

**Comment by nguyen37** [comment]
Oh shoot.. I was thinking it had to be one lower.. going to close, sorry about this
