### ISSUE TITLE
No Solution Found

### ISSUE THREAD

**Issue by aviv943** [Xenogents/LegionSolver#44]
I only have the option of 21 characters with 85 slots. No matter what combination I try in the grid, it gives a No Solution Found error. You can see in the picture that it also does not fill everything that can be filled, and immediately throws an error.

https://i.imgur.com/Rlfvs5v.png

**Comment by Xenogents** [comment]
It's cause you're giving it something impossible, too many corners and not enough stuff to fill those corners.
