### ISSUE TITLE
Request: Abysal Expedition: El Nath block

### ISSUE THREAD

**Issue by HikariCalyx** [Xenogents/LegionSolver#45]
In CMS, shape should be this:
```
    // Lvl 250 Abyssal expedition: El Nath
    [
        [1, 1, 0],
        [0, 2, 1],
        [0, 0, 1]
    ],
```

Proper translation:
```
深渊远征队：冰峰雪域
```

I'll inform later for the final shape and decide if we should implement, since it's directly extracted from game data. CMS doesn't have the shape mentioned in patch notes.

**Comment by Xenogents** [comment]
Ok let me know.

**Comment by HikariCalyx** [comment]
Sadly, the shape is same as SS Pirate according to CMS player feedback.
As for TMS, the shape is same as SSS Bowman.
Therefore the issue is closed.
![1717603644233](https://github.com/Xenogents/LegionSolver/assets/29157608/0ffacc5d-0902-4256-b438-6b5c42cfc9a9)
